export const FETCH_COURSES_REQUEST = 'FETCH_COURSES_REQUEST';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const FETCH_COURSES_FAILURE = 'FETCH_COURSES_FAILURE';

export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';
export const REQUEST_ADD_COURSE = 'REQUEST_ADD_COURSE';
export const REQUEST_UPDATE_COURSE = 'REQUEST_UPDATE_COURSE';

export const SUCCESS_ADD_COURSE = 'SUCCESS_ADD_COURSE';
export const SUCCESS_UPDATE_COURSE = 'SUCCESS_UPDATE_COURSE';
export const ERROR_ADD_COURSE = 'ERROR_ADD_COURSE';

export const ERROR_UPDATE_COURSE = 'ERROR_UPDATE_COURSE';